### ISSUE TITLE
The incompressible elasticity example does not work 

### ISSUE THREAD

**Issue by Abdulmalik-SoftMatter** [Ferrite-FEM/Ferrite.jl#1047]
when I run the example I get this.

```
MethodError: no method matching add!(::DofHandler{2, Float64, Grid{2, Triangle, Float64}}, ::Symbol, ::Int64, ::Lagrange{2, RefTetrahedron, 1})

Stacktrace:
 [1] create_dofhandler(grid::Grid{2, Triangle, Float64}, ipu::Lagrange{2, RefTetrahedron, 1}, ipp::Lagrange{2, RefTetrahedron, 1})
   @ Main .\In[4]:3
 [2] solve(ν::Float64, interpolation_u::Lagrange{2, RefTetrahedron, 1}, interpolation_p::Lagrange{2, RefTetrahedron, 1})
   @ Main .\In[9]:11
 [3] top-level scope
   @ In[10]:4
```
I tried copying line by line from the example and I tried to download the notebook and run it locally but all give the same problem

**Comment by AbdAlazezAhmed** [comment]
Hi, I think you might be running the example from last release while using master or an updated branch.
see https://github.com/Ferrite-FEM/Ferrite.jl/commit/cab433f54a214f98303694a5f5447b31defa9853#diff-23be3377b7d3c760b88b7cfb26fd74058fe93226cfeaeed0611b964796348f91L60-L66
The example in master is working fine for me.

**Comment by fredrikekre** [comment]
If you are using the latest release (0.3.14) then these are the corresponding docs: https://ferrite-fem.github.io/Ferrite.jl/v0.3.14/examples/incompressible_elasticity/
If you are using the master branch of Ferrite, then these are the corresponding docs: https://ferrite-fem.github.io/Ferrite.jl/dev/tutorials/incompressible_elasticity/
