### ISSUE TITLE
Having to send a time into the function for constraints is a design failure.

### ISSUE THREAD

**Issue by KristofferC** [Ferrite-FEM/Ferrite.jl#207]
This should just be handled by sending in a closure `f(x) = f(x, t, ...)`.

**Comment by fredrikekre** [comment]
So `t` should be a global variable then?

**Comment by KristofferC** [comment]
No, t can be a local variable and you send in the closure `x -> f(x, t)`. Just like always when you need to pass parameters.

**Comment by fredrikekre** [comment]
But we give the function only once, when creating the condition.

**Comment by fredrikekre** [comment]
TIL

**Comment by fredrikekre** [comment]
Another proposal: Let user define `f(x, args...; kwargs...) -> value` and then call `update!(ch, args...; kwargs...)` as appropriate. `update!` would then splice in the `x` as `f(x, args...; kwargs...)`.

**Comment by fredrikekre** [comment]
Maybe a `NamedTuple` is appropriate? User defines `f(x, nt) -> value` and call `update!(ch, nt)`.

**Comment by KristofferC** [comment]
Maybe, but I wonder if not just propagating `args...; kwargs...` (like you have in the PR I think) is easier in that case.
