### ISSUE TITLE
Don't assume the same number of dofs on egdes/faces

### ISSUE THREAD

**Issue by lijas** [Ferrite-FEM/Ferrite.jl#272]
I want to create an continuum-shell element with n number of dofs on edges in the thickness direction, and zero edge-dofs inplane. Currently the DofHandler assumes the same number of edge-dofs on all edges.

Possible fix: Make `nedgedofs(::Interpolation)` specify number of dofs for each edge.

`nvertexdofs(::ShellInterpolation) = 1`
`nedgedofs(::ShellInterpolation)   = (3,3,3,3, 0,0,0,0, 0,0,0,0)`
`nfacedofs(::ShellInterpolation)   = 1 #Maybe same change here`
`ncelldofs(::ShellInterpolation)   = 0`
So the four "out-of-plane"-edges will have three edge-dofs, and the other edges will not have any...
This also makes the direction of the element important...

I think this would only require small changes in close!(dofhandler)`

**Comment by fredrikekre** [comment]
Closed by #581, I think.
