### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#274]

**Comment by fredrikekre** [comment]
Femzilla

**Comment by fredrikekre** [comment]
Femgnx

**Comment by JimBrouzoulis** [comment]
FEMatron

**Comment by fredrikekre** [comment]
Feya

**Comment by fredrikekre** [comment]
Femly

**Comment by fredrikekre** [comment]
Femio (med fem.io som webadress)

**Comment by fredrikekre** [comment]
Femlux

**Comment by fredrikekre** [comment]
Femify

**Comment by fredrikekre** [comment]
Fedo

**Comment by fredrikekre** [comment]
Feverse

**Comment by fredrikekre** [comment]
Femya

**Comment by lijas** [comment]
CoolFem

**Comment by lijas** [comment]
FEkre

**Comment by KristofferC** [comment]
Ferrite.jl

**Comment by koehlerson** [comment]
> Femly

Femily - bringing together computational scientist with dyslexia

**Comment by KristofferC** [comment]
Felicia.jl, from @lijas

**Comment by mforets** [comment]
more names:

- FEMToolbox.jl
- SimpleFEM.jl
- Feng.jl, for [Feng Kang](https://en.wikipedia.org/wiki/Feng_Kang)
- Clough.jl, for [R. W. Clough](https://en.wikipedia.org/wiki/Ray_William_Clough)

**Comment by koehlerson** [comment]
Galerkin.jl

**Comment by termi-official** [comment]
Probably something in the direction of

* FiniteElementToolkit.jl
* FEToolkit.jl
* FiniteElementTools.jl
* FETools.jl
* FiniteElementFoundation.jl
* FEFoundation.jl

**Comment by mohamed82008** [comment]
So the most popular ones thus far here seem to be:
- Ferrite.jl
- Felicia.jl
- Feverse.jl

How do you plan to resolve this? A vote?

**Comment by mohamed82008** [comment]
If this is blocking the package registration, any chance to resolve this soon?

**Comment by KristofferC** [comment]
After some discussion, the final choice was: "Ferrite.jl".

**Comment by mohamed82008** [comment]
Is the change going to happen soon?

**Comment by KristofferC** [comment]
Yeah, I just don't know if renaming the existing repo vs making a new repo is the best way forward.

Renaming the repo has advantages in that all open PRs and the history of all isuees/PRs is kept. But the drawback is that people who do `add https://github.com/KristofferC/JuAFEM.jl` will get Ferrite.jl and be confused.

**Comment by mohamed82008** [comment]
I think the confusion is inevitable until people get used to the name change. Hopefully when Ferrite gets registered, less people will be using the full url and confusion will naturally decay.

**Comment by KristofferC** [comment]
Sure, but the question is if the initial pain of renaming the repo is worth it over losing the history with a new repo.

**Comment by KristofferC** [comment]
Done
