### ISSUE TITLE
Maybe remove the fallback `vtk_point_data`

### ISSUE THREAD

**Issue by KristofferC** [Ferrite-FEM/Ferrite.jl#278]
Today I spent ~4 hours wondering why my exports looked like:

<img width="718" alt="Screenshot 2020-03-09 at 14 35 40" src="https://user-images.githubusercontent.com/1282691/76221847-002f6800-621a-11ea-838a-95eb6f8d278b.png">

(note the weird looking thing in the second row).

Turns out that I wrote

```jl
vtk_point_data(vtk, u, "u")
```

Instead of

```jl
vtk_point_data(vtk, dh, u, "u")
```

This meant that this function got used:

https://github.com/KristofferC/JuAFEM.jl/blob/8224282ab4d67cb523ef342e4a6ceb1716764ada/src/Export/VTK.jl#L58-L63

instead of the one that takes into account the order of the dofs. Maybe we should just call it `_vtk_point_data` or something?

**Comment by koehlerson** [comment]
Well, after several hours of "debugging" I found out that I reproduced exactly this. Big brain time. So, +1 for removing it
