### ISSUE TITLE
apply! without modifying A

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/Ferrite.jl#280]
In the case of solving a time-dependent linear problem, one only assembles once and therefore, only needs to modify the stiffness matrix once. Currently, the possible workaround is to copy A in each time step, let it modify with the rhs vector and solve with `copyA \ b` (see https://discourse.julialang.org/t/understand-apply-of-juafem/35325/7). In general, this is not harmful or expensive, but for some use cases this can become quite alloc expensive. In my particular case I'm solving in the source/sink term within each Gauss point another transient diffusion problem. 

Hence, it makes sense to factor out
 https://github.com/KristofferC/JuAFEM.jl/blob/5867e06faef8e8c86076c176f30357f8526c107d/src/Dofs/ConstraintHandler.jl#L344-L353

 and 

https://github.com/KristofferC/JuAFEM.jl/blob/master/src/Dofs/ConstraintHandler.jl#L372

 to provide an apply! function that only alters b

**Comment by KristofferC** [comment]
Fixed in https://github.com/Ferrite-FEM/Ferrite.jl/pull/304
