### ISSUE TITLE
CellIterator not working at all if called without dof handler

### ISSUE THREAD

**Issue by sebastianpech** [Ferrite-FEM/Ferrite.jl#289]
I used to simply call the `CellIterator` with `CellIterator(grid)`. However, this doesn't work anymore.
The problem is, that in the constructor for the grid only case

https://github.com/KristofferC/JuAFEM.jl/blob/20d14ac223598c926d13023a511a48f0c5c1ce33/src/iterators.jl#L47-L54

`cellset`, `dh` and `celldofs` are not passed when creating the type. The last two are obvious as no info about dofs is provided, however not passing `cellset` seems to be an error. Tried to fix it that way, but 

https://github.com/KristofferC/JuAFEM.jl/blob/20d14ac223598c926d13023a511a48f0c5c1ce33/src/iterators.jl#L88-L89

needs `dh` to be set, so my code always runs into an `UndefRefError`. MWE:

```
grid = generate_grid(Triangle, (20, 20))
for cell in CellIterator(grid)
    @show "foo" # This never prints
end
```

So is the grid only method still supported?

**Comment by lijas** [comment]
I did some changes to CellIterator a while back, but I did not add tests etc. Since It was me who broke it, I can see if I can fix it now :sweat_smile:

**Comment by KnutAM** [comment]
The example is working now. 
I suppose fixed by https://github.com/Ferrite-FEM/Ferrite.jl/pull/301, 
so I think this can be closed...
