### ISSUE TITLE
How to set up CompatHelper in a package that depends on JuAFEM.jl?

### ISSUE THREAD

**Issue by dkarrasch** [Ferrite-FEM/Ferrite.jl#310]
We have a package called CoherentStructures.jl that depends on this package here. The default CompatHelper workflow fails due to some "Unsatisfiable requirements detected for package JuAFEM", see https://github.com/CoherentStructures/CoherentStructures.jl/actions/runs/416585115. Has anyone in the same situation got CompatHelper running? Any advice would be highly appreciated.

**Comment by koehlerson** [comment]
Try to add JuAFEM explicitely in your workflow file, e.g. : https://github.com/koehlerson/ConvexDamage/blob/master/.github/workflows/main.yml

**Comment by dkarrasch** [comment]
Thanks @koehlerson, that helps only in the ci and the documentation workflows, but not in the CompatHelper workflow... 😞

**Comment by fredrikekre** [comment]
I'm guessing then that this should be a feature request to CompatHelper to make it possible to use undregistered packages.

I guess what we really should do is to come up with a nicer name (https://github.com/KristofferC/JuAFEM.jl/issues/274) and register this package...

**Comment by fredrikekre** [comment]
Btw, what happens if you commit a manifest to the repo?

**Comment by dkarrasch** [comment]
> Btw, what happens if you commit a manifest to the repo?

I'll give that a try. We have one in the docs, but not for the package.
