### ISSUE TITLE
L2Projection does not work accurately for mixed grids

### ISSUE THREAD

**Issue by kimauth** [Ferrite-FEM/Ferrite.jl#330]
For mixed grids, the L2Projection can only handle one cell type at a time. So e.g. for a grid composed of triangular and quadrilateral elements, we can do a projection within the triangular elements and another (independent) projection within the quadrilateral elements. But if we have a field that lives on both element types, we would want to do one projection of the field onto all nodes. I'll leave this issue a reminder to implement that (and a warning in case someone uses it for mixed grids).

**Comment by termi-official** [comment]
Just to discuss it here openly: Wouldn't it be benificial to solve this issue in another way, as we discussed earlier over zoom, i.e. by trying to provide a unified iteration interface over different types of elements (opposing the current state of separating the iteration over different types of elements)?

**Comment by kimauth** [comment]
Possibly, but I would say that's rather a conceptual question how to handle mixed grids in general. (Or am I misunderstanding you?)

It is possible to fix the L2Projection of fields on mixed grids with the current approach (by the `MixedDofHandler`) - I just can't implement it right now, thus the reminder.

**Comment by fredrikekre** [comment]
@kimauth this is resolved right?

**Comment by KnutAM** [comment]
https://github.com/Ferrite-FEM/Ferrite.jl/pull/949
