### ISSUE TITLE
JuliaPDE survey update?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [Ferrite-FEM/Ferrite.jl#349]
Would it be possible to update the survey of PDE packages, as I understand the JuAFEM package has been replaced by this one?
Thanks!

**Comment by KristofferC** [comment]
> Would it be possible to update the survey of PDE packages,

I don't really understand what that means. But yes, JuaFEM got renamed to Ferrite.

**Comment by koehlerson** [comment]
https://github.com/JuliaPDE/SurveyofPDEPackages

It's about this overview

**Comment by KristofferC** [comment]
https://github.com/JuliaPDE/SurveyofPDEPackages/pull/34 I guess then.
