### ISSUE TITLE
No examples with `MixedDofHandler`

### ISSUE THREAD

**Issue by kimauth** [Ferrite-FEM/Ferrite.jl#355]
We don't seem to have any examples that use the `MixedDofHandler`. Any ideas of simple applications?
Main points that the `MixedDofHandler` can do that the `DofHandler` can't would be

- a grid with different celltypes in it 
- a problem with several fields where one of the fields lives only on a part of the domain.

**Comment by koehlerson** [comment]
https://www.dealii.org/current/doxygen/deal.II/step_46.html

**Comment by koehlerson** [comment]
Piezoelectric actuator could also be a nice example for `MixedDofHandler`
