### ISSUE TITLE
Grid inconsistencies

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/Ferrite.jl#394]
There are a few inconsistencies related to the `Grid` type

- We have in `Grid` the cellsets defined as `Dict{String,Set{Int}}`, but I guess we should use `Dict{String,Set{CellIndex}}` https://github.com/Ferrite-FEM/Ferrite.jl/blob/a8b06904d15946483cc14e3656217ed2c279777e/src/Grid/grid.jl#L105
- `compute_vertex_values` should probably renamed to `compute_nodal_values` since the vertex is defined as the corners of a cell and neglects the "higher order" nodes
https://github.com/Ferrite-FEM/Ferrite.jl/blob/a8b06904d15946483cc14e3656217ed2c279777e/src/Grid/grid.jl#L246-L260 
 I don't know who or what part of Ferrite uses this function, but strictly speaking this would be a breaking change. Although easy to fix for everyone.
 
 @termi-official edit the issue or write me if I forgot something

**Comment by termi-official** [comment]
We also should check for more definition inconsistencies in what edges and faces are.

**Comment by KnutAM** [comment]
I tried to get a bit of an overview of the grid interface and figured I could share my notes/thoughts here. I found a few (probably known) inconsistencies and made some suggestions on how they could be fixed. Also related to the `get*(...)` vs `*(...)` issue... 

## Grid interface
### Coordinates
* `getcoordinates`
  * `Grid, Int` -> Cell coordinates
  * `Node` -> **Node** coordinates
  * `Grid, FaceIndex` -> Cell coordinates
  * `CellCache` -> Cell coordinates

* `getcoordinates!`
  * `x, Grid, Union{Int,Cell,CellIndex,FaceIndex}`: `x` -> Cell coordinates

* `Ferrite.cellcoords!`
  * `x, Union{[Mixed]DofHandler,Grid}, n::Int`: `x`->Cell coordinates

* `Ferrite.get_coordinate_eltype(::Union{Grid,Node})` returns the `T` in `Vec{dim,T}`

### Nodes
* `getnodes`
  * `Grid` -> `::Vector{Node}`
  * `Grid, Int` -> `Node`
  * `Grid, Union{String,Vector{Int}}` -> `Vector{Node}`

* `Ferrite.cellnodes!`
  * `ids::Vector{Int}, Union{Grid,MixedDofHandler}, Int`: `ids` -> The cell's node numbers

### Cells
* `cellid`
  * `CellCache` -> cell index in the grid
  * `PointLocation` -> cell index in the grid 
* `getcells`
  * `Grid` -> All `Cell`s in the grid
  * `Grid, id::Int` -> Return `Cell` nr `id`
  * `Grid, v::Union{Vector,String}` -> Return all `Cell`s in the set described by `v`
  * Various `EntityNeighborhood` -> ***Returns the cell id, `::Int`***
* `getcelltype`
  * `Grid` -> The grid's celltype (possible abstract)
  * `Grid, id::Int` -> The concrete celltype of cell `id`

### Faces, edges, vertices
* `vertices`
  * `Interpolation`: Return the local node indices for the vertices in a `Cell` described by `Interpolation`
  * `Cell`: Return the global node numbers for the vertices in the `Cell`
* `edges`
  * `Interpolation`: Return the local node indices that describe the edges in a `Cell` described by `Interpolation`
  * `Cell`: Return the global node numbers for the nodes that describe the edges in the `Cell`
* `faces`
  * `Interpolation`: Return the local node indices that describe the faces in a `Cell` described by `Interpolation`
  * `Cell`: Return the global node numbers for the nodes that describe the faces in the `Cell`

*Side-thought:* This seems to strengthen having `Cell{IP<:Interpolation}`: 
Functions calling `*(::Cell{IP})` can use the output from `*(::IP)`. 

## Ideas for changes
### Deprecation and replacement
* `getcoordinates`->
  * `get_node_coordinates(::Node)`, `get_node_coordinates(::Grid, n::Int)`
  *  `get_cell_coordinates(::Grid, ::Int)`
* `getcoordinates!` -> `cellcoords!` (only `get`-function with `!` ?) (Except `Ferrite.get_or_create_dofs!` which isn't pure `get`)
* `cellnodes!` -> `cellnodeids!`
* `cellid` -> `getcellid`. Add `getcellid(Union{FaceIndex,EdgeIndex}`
* `getcells(::EntityNeighborhood`) -> `getcellid`
    
## Suggestion for new methods
* `get_face_coordinates(::Grid, ::FaceIndex)`
* `get_edge_coordinates(::Grid, ::EdgeIndex)`
* `getnodeid(::AbstractCell, n::Int)` -> As name says
* `getfaceid(id::FaceIndex)=id[2]` 
* `get_coordinate_type(::AbstractGrid[, i::Int])`, i.e. `Vec{3,Float64}`

### Personal thoughts on naming
* `get*` is good for getting things, e.g. `getnodes`
* `*!` is good for mutating methods, e.g. `cellnodes!`

I have often wanted to write `ndofs=ndofs(dh)` ...

**Comment by termi-official** [comment]
Note that I suggest a renaming of `vertices`, `faces` and `edges` in #581 to disambiguate.

**Comment by KnutAM** [comment]
> Note that I suggest a renaming of `vertices`, `faces` and `edges` in #581 to disambiguate.

Nice change! 

> Edit: Also note that `vertices`, `faces` and `edges` have different semantics for cells and interpolations.

Im not sure if I follow, do you mean something else than that they return global vs local indices?

**Comment by termi-official** [comment]
For cells the corresponding vertex node indices are returned while for interpolations all local dof indices on the closure of the entity are returned. E.g. for a quadratic triangle with quadratic Lagrange interpolation faces(cell) would return something like ((1,3),(3,2),(2,1)) while faces(ip) returns something like ((1,3,4),(3,2,5),(2,1,6)).

**Comment by termi-official** [comment]
Related comment for reference https://github.com/Ferrite-FEM/Ferrite.jl/pull/743#discussion_r1254353892 : Is the vertex in 1D a face?

**Comment by fredrikekre** [comment]
I think this is all handled.
