### ISSUE TITLE
FerriteMeshParser

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#424]
[FerriteMeshParser](https://github.com/KnutAM/FerriteMeshParser.jl) currently only supports Abaqus input files but could be extended to other formats as well. This issue is for discussing whether this code should be included in Ferrite.jl, or kept as a separate package. 

Suggestions for discussion points
1. Should FerriteXYZ packages be limited to those requiring external dependencies?
2. Is it a problem to include a lot of file reading code into Ferrite.jl (I guess this is where the code would mostly grow if more formats are added)
3. How to interact with `FerriteGmsh.jl` (@koehlerson). I would find it nice with the same interface when reading Gmsh and Abaqus?

**Comment by kimauth** [comment]
I don't think Ferrite itself needs to support reading external mesh formats. As you say, the amount of code for supporting different formats can become quite large. From my perspective having packages like `FerriteGmsh.jl` is a good solution for this. Sure it would be nice if the same syntax was supported for different file formats, but it's usually just one line of code for importing the mesh, so I don't think its crucial to have a standard syntax. I usually don't switch mesh formats, it's not really a hassle to just change that line when using another package.

**Comment by koehlerson** [comment]
I can rename the functions in `FerriteGmsh`, however, keep in mind that `FerriteGmsh` is a bit different, since it doesn't really parse the mesh file itself but rather calls the gmsh API to parse it. This allows for relatively less code and guaranteed compatibility with the gmsh `msh` formats. Due to the gmsh API structure, we are quite limited in how to design stuff, since the gmsh API works with global states, which is from a julia package perspective not really desirable.

**Comment by KnutAM** [comment]
I also agree that keeping it separate is cleaner. One option then for FerriteGmsh is that FerriteMeshParser can do something like
```julia
function __init__()
    @require FerriteGmsh="4f95f4f8-b27c-4ae5-9a39-ea55e634e36b" include("ferrite_gmsh_glue_code.jl")
end
```
using [Requires.jl](https://github.com/JuliaPackaging/Requires.jl) such that if FerriteGmsh is loaded, the user can do `get_ferrite_grid("meshfile.msh")` In that case no changes are required on FerriteGmsh's side.
As far as I understand, there are some precompilation performance issues with Requires, but should be ok for the parser package.

**Comment by termi-official** [comment]
Kim has a good point here. Note that the mesh formats are wildly different, which makes "one interface" to them quite difficult. Some formats even have rich meta data which is not available in our `Grid` struct such that a new subtype of `AbstractGrid` may make sense.

**Comment by KnutAM** [comment]
Ah, I see, I think I might have misread the earlier comments, sorry about that! But then I think this issue can be closed - thanks a lot for the feedback! 
l'll move the meshparser to the ferrite-org later this week!
