### ISSUE TITLE
Remove `ScalarWrapper`s and use `const` fields instead

### ISSUE THREAD

**Issue by KristofferC** [Ferrite-FEM/Ferrite.jl#488]
```
mutable struct Foo
    a::Int
    const b::Int
end
```

Added in Julia 1.8. Can use that when we drop pre 1.8.

**Comment by KnutAM** [comment]
Should we drop julia 1.6 for 1.0 then @fredrikekre, or should this be [v1.X](https://github.com/Ferrite-FEM/Ferrite.jl/milestone/2) ?

**Comment by fredrikekre** [comment]
Can use something like https://github.com/fredrikekre/Prometheus.jl/blob/master/src/Prometheus.jl#L56-L62 and https://github.com/fredrikekre/Prometheus.jl/blob/cc82e4286dd23d365a39045182806d8fbecb6e92/src/Prometheus.jl#L142 to have things working on 1.6 for a bit longer I guess.

**Comment by KnutAM** [comment]
Just adding a note here that this requires benchmarking `FacetValues` usage, since these can be performance-critical.
