### ISSUE TITLE
The bug of "greedy"- algorithm in Threaded Assembly

### ISSUE THREAD

**Issue by zkk960317** [Ferrite-FEM/Ferrite.jl#502]
When I run the "Example of a colored 2D grid" in "Threaded Assembly" with Julia 1.8.2, I cannot get the four-color chessboard as the document shows. Instead, I get a seven-color pattern. After analyzing the source code, I found that this bug can be repaired by following step.

Modify the code `return greedy_coloring(incidence_matrix, cellset)` to `return greedy_coloring(incidence_matrix)` at Line 194 of file "coloring". 

I think the reason is that "cellset" is an unordered set, but the default 2nd parameter of function "greedy_coloring" is `cells=1:size(incidence_matrix, 1)` is an ordered set, which is right.

**Comment by fredrikekre** [comment]
The order should not matter, it is just that the sorted order works best for this particular mesh with this particular element numbering, I believe.
