### ISSUE TITLE
inconsistent higher order node between RefCube and RefShape

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/Ferrite.jl#520]
the ordering seems not consistent between second order tet and cube

https://github.com/Ferrite-FEM/Ferrite.jl/blob/master/src/interpolations.jl#L548
https://github.com/Ferrite-FEM/Ferrite.jl/blob/master/src/interpolations.jl#L460

Tetrahedron goes first order - second order - first order
Cube edge is defined as first order - first order - second order

**Comment by kimauth** [comment]
This is only true for 3D, right? At least the 2D quadratic tetrahedron goes first order - first order - second order: https://github.com/Ferrite-FEM/Ferrite.jl/blob/084a7c9d967047efa986dcb3ac0668033e023084/src/interpolations.jl#L310

**Comment by koehlerson** [comment]
yes, this is only in 3D inconsistent :)
