### ISSUE TITLE
Support for Wedge&Pyramid elements

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#580]
We are currently missing support for two rather common elements for complex geometries, namely 
* [x] wedges #581
* [ ] pyramids #623

However, this might not be straight forward, because these elements have different face geometries, breaking some of the internal assumptions on having the same face geometry on each face.

This could also pave the way for more generalized formulations (e.g. virtual elements).

**Comment by KnutAM** [comment]
That would be nice!
When this issue is solved, please open an issue for FerriteMeshParser.jl to change the example: https://ferrite-fem.github.io/FerriteMeshParser.jl/stable/examples/user_element/
