### ISSUE TITLE
Rename `Ferrite.value` and `Ferrite.derivative`

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#609]
We now have
https://github.com/Ferrite-FEM/Ferrite.jl/blob/84e9aefd1cafc54d6aefd4587cecbf0e555d20f6/src/interpolations.jl#L65
and
https://github.com/Ferrite-FEM/Ferrite.jl/blob/84e9aefd1cafc54d6aefd4587cecbf0e555d20f6/src/interpolations.jl#L76
for computing the value and derivate of shape functions in the reference domain. These are not great names. We could (re)use `shape_value` and `shape_gradient` which is already used for `CellValues`, but in that case it is not in the reference domain, and would also "leak" these internal methods.

I don't have any good ideas,  hence the issue, but perhaps `reference_shape_value` and `reference_shape_gradient`.

**Comment by KnutAM** [comment]
One suggestion could be `compute_shape_value` and `compute_shape_gradient` (or `calculate_*`)
