### ISSUE TITLE
L2Projector for mixed grids

### ISSUE THREAD

**Issue by lijas** [Ferrite-FEM/Ferrite.jl#610]
It would be nice to be able to use the L2Projector if you have a domain with mixed celltypes, and you want to L2Project over the entire domain. Currently it is only possible to l2Project over one celltype at a time.

Possible api:

```
#init alt1:
projector = L2Projector(grid, set=mixedset) #Creates mass-matrix internaly

#init alt2:
projector = L2Projector(grid)
load_massmatrix!(projector, ip_hex, cellset1)
load_massmatrix!(projector, ip_tet, cellset2)

#...

# Create rhs:
load_forcevector!(projector, σqp1, qr_hex, cellset1)
load_forcevector!(projector, σqp2, qr_tet, cellset2)
σ_nodes = project(projector; project_to_nodes=true); 
```

**Comment by termi-official** [comment]
I think it makes sense to merge the dof handlers first and then make one feature at a time consistent with mixed grids. What do you think?

**Comment by KnutAM** [comment]
Are breaking changes required for this, or can this be done post 1.0?
