### ISSUE TITLE
find_field and field_offset broken for MixedDofHandler

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#613]
Reproducer

```julia
   dim = 2
   mesh = generate_grid(Quadrilateral, (2,1))
   addcellset!(mesh, "set1", Set(1))
   addcellset!(mesh, "set2", Set(2))

   ip = Lagrange{dim, RefCube, 1}()
   field_u = Field(:u, ip, dim)
   field_c = Field(:c, ip, 1)

   dh = MixedDofHandler(mesh)
   add!(dh, FieldHandler([field_u], getcellset(mesh, "set1")))
   add!(dh, FieldHandler([field_u, field_c], getcellset(mesh, "set2")))
   close!(dh)

  Ferrite.find_field(dh, :c)
```

**Comment by lijas** [comment]
The function `Ferrite.find_field(dh::MixedDofHandler, :c)` assumes that there is only one `FieldHandler` in the `MixedDofHandler`. I think I added the function `Ferrite.find_field(dh::MixedDofHandler, :c)` way back when I tried to merge the two dofhandlers

It is probably the function `Ferrite.find_field(field_c, :c)` that should be used.  But I agree, this is not good and should fixed.

**Comment by KnutAM** [comment]
There is also `nnodes_per_cell(dh::MixedDofHandler, cell=1)` which perhaps should be deprecated as for non-concrete grids, and `cell` should be required (alternatively giving the fieldhandler)

**Comment by termi-official** [comment]
There are indeed several of these functions. I just wanted to open an issue here because I usually forget to open one when I find such a minor bug in the internals.

Exact design of these functions has to be determined when the dof handlers are merged.

**Comment by termi-official** [comment]
Closed by https://github.com/Ferrite-FEM/Ferrite.jl/pull/621
