### ISSUE TITLE
Topology construction is slow

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#617]
Implementation of the topology construction is quite slow right now and can be optimized (type stability, allocations, ...).

Concrete ideas are
1. [ ] Preallocate sparsity pattern
2. [ ] Preallocate buffers with sufficient size to reduce allocations
3. [ ] Separate mixed dimensional code path from non-mixed dimensional code path

**Comment by termi-official** [comment]
I added this to the next milestone, because this is a potentially breaking change.

**Comment by termi-official** [comment]
Should I leave this open, because topology construction it is still not that fast?

**Comment by koehlerson** [comment]
Let's keep it open, sorry was autoclosing due to merging
