### ISSUE TITLE
Use OrderedSet for cellsets

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#631]
I think we should use `OrderedSet`s from https://github.com/JuliaCollections/OrderedCollections.jl for, at least, the cellsets in the grid. This will ensure that we have both fast lookup and that we can iterate cells in order. This will require https://github.com/JuliaCollections/OrderedCollections.jl/pull/100 and a new release of that package so that we can `sort!` in the `Grid` constructor and in `addcellset`.

xref discussion in https://github.com/Ferrite-FEM/Ferrite.jl/pull/625

**Comment by termi-official** [comment]
Should I address this already in the linked PR or leave it as a good first issue?

**Comment by fredrikekre** [comment]
This could probably be pretty self-contained PR (easier to review). Opened this mostly to see if people liked the idea :)

**Comment by lijas** [comment]
What's the drawback between ordered sets and normal sets? :)

**Comment by koehlerson** [comment]
> What's the drawback between ordered sets and normal sets? :)

If the problem is big and you iterate over the set, i.e. unordered, you need to visit very different chunks of data for e.g. internal variables

**Comment by termi-official** [comment]
The bigger issue is that "normal" sets are unordered and ordering may even mutate. E.g. you cannot easily iterate over the entries in ascending order.
