### ISSUE TITLE
Dof distribution slow

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#632]
The current dof distribution algorithm works well, but it is also very slow. This can be a deal-breaker for problems with changing mesh topology of on problems where multiple dof handlers may be used. We should explore different strategies to distribute the dofs faster, (e.g. via fast paths or by using additional information that can be precomputed).

Minimal example is takes from Kim ( #629 )

```
using Ferrite
using BenchmarkTools

grid = generate_grid(Quadrilateral, (1000, 1000))
ip_v = Lagrange{2,RefCube,2}()
ip_s = Lagrange{2,RefCube,1}()

function setup_close(grid, T)
    dh = T(grid)
    add!(dh, :v, 2, Lagrange{2,RefCube,2}()) 
    add!(dh, :s, 1, Lagrange{2,RefCube,1}()) 
    return dh
end

@btime close!(dh) setup=(dh=setup_close($grid, $DofHandler)) evals=1; # 1.542 s (224 allocations: 565.04 MiB)
```

**Comment by kimauth** [comment]
I'm sure there are things that could be optimised in the dof distribution, but is ~0.65 s really that slow for a problem with ~9e6 dofs? Wouldn't the assembly or the linear solve be much more likely candidates for a performance bottleneck at that system size?

**Comment by KristofferC** [comment]
I would also push back a little bit about calling this "very slow" but yeah, I am sure the performance can be improved.

As it is right now the cost is basically completely in dictionary lookups in the part where we check if a dof has already been assigned to a certain entity.

**Comment by fredrikekre** [comment]
>  it is also very slow

https://github.com/Ferrite-FEM/Ferrite.jl/pull/643#issue-1640279870

![image](https://user-images.githubusercontent.com/11698744/227675407-8c9e3707-17ec-42f7-ad39-0060ee468dfc.png)

**Comment by termi-official** [comment]
![sonic-the-hedgehog-classic-sonic](https://user-images.githubusercontent.com/9196588/227679153-4703711e-3fa5-4ba2-9f18-c6b4cffad6c7.gif)

Will take a look at eliminating the other two dicts.
