### ISSUE TITLE
(Face|Cell)(Scalar|Vector)Values -> (Face|Cell)Values

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#682]
Perhaps we can combine scalar and vector values into a single struct. The `CellScalarValues` and `CellVectorValues` structs are almost identical:
https://github.com/Ferrite-FEM/Ferrite.jl/blob/32d2a589fafe2a01bf5e992aa263997a65532c75/src/FEValues/cell_values.jl#L37-L49

https://github.com/Ferrite-FEM/Ferrite.jl/blob/32d2a589fafe2a01bf5e992aa263997a65532c75/src/FEValues/cell_values.jl#L89-L101

It should be possible to combine these into something like:

```julia
struct CellValues{N_t, dNdx_t, ...}
    N::Matrix{N_t}
    dNdx::Matrix{dNdx_t}
    dNdξ::Matrix{dNdξ_t}
    detJdV::Vector{T}
    M::Matrix{T}
    dMdξ::Matrix{dMdξ_t}
    qr::QR
    func_interp::IPF
    geo_interp::IPG
end

const CellScalarValues = CellValues{<: Number}
const CellVectorValues = CellValues{<: AbstractVector}
const CellMatrixValues = CellValues{<: AbstractMatrix}
```

We only use the distinction for e.g. https://github.com/Ferrite-FEM/Ferrite.jl/blob/32d2a589fafe2a01bf5e992aa263997a65532c75/src/FEValues/common_values.jl#L107 which you can then instead dispatch on `CellValues{<:AbstractVector}`.

Question is if it is worth it.

**Comment by termi-official** [comment]
I kinda like the idea, as it allows to us address several open issues in a simpler way (e.g. complex-valued problems and general tensor-valued problems, ...) and we can reduce some code duplication. However, I am not super confident regarding the interaction with Tensors.jl here, as well as with constraints between the types which are necessary to avoid performance issues.
