### ISSUE TITLE
Workspace/additional data for interpolations in CellValues

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#683]
To generalize `CellValues` I think interpolations should be able to store stuff in an additional struct field, e.g.
```julia
struct CellValues{..., IPD}
   # ...
   interpolation_data::IPD
end
```

Two usecases:
1. Interface elements (and I suppose regular embedded elements) it is useful to store the rotation, see e.g. https://github.com/kimauth/FerriteCohesiveZones.jl/blob/fa274d16020ff33e0772a882136c4c46ee630951/src/cohesive_values.jl#L13. This is used to rotate [to](https://github.com/kimauth/FerriteCon2022.jl/blob/21aac15b1a467236eb7e8bae2380f8062c3b14a2/src/element_routine.jl#L44) and [from](https://github.com/kimauth/FerriteCon2022.jl/blob/21aac15b1a467236eb7e8bae2380f8062c3b14a2/src/element_routine.jl#L49-L50) the local coordinate system. Currently this is solved by defining a new `CohesiveVectorValues` struct https://github.com/kimauth/FerriteCohesiveZones.jl/blob/fa274d16020ff33e0772a882136c4c46ee630951/src/cohesive_values.jl#L4 but I think this wouldn't be necessary if the interpolation could ask to store this in the extra field instead. In that case, passing an interface interpolation to the regular CellValues would just work
2. Vector-valued elements (RT, Nedelec) need to permute and change sign of their base functions during `reinit!`. This means that we need to store `N(ξ)` somewhere, and store the mapped value, with sign/permutation in the `N(x)` field of the current `CellValues` struct.

**Comment by lijas** [comment]
1. I think  in special cases like Cohesive zones, shell elements etc, it is difficult to generalise  CellValues in such a way that they would work for all special element types. IMO there is no benift to just subtype Values and try to reuse the functions defined in common_values.jl as much as possible.

2. Maybe N(ξ) can just be stored as fields instead?

Sorry for being so negative :smile:
