### ISSUE TITLE
Safety net for for vtk export

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#686]
Currently `vtk_point_data` does not necessarily error if we do something stupid, and does not even warn us. We should at least add some warnings and possibly stop with some meaningful error message if possible.

**Comment by KristofferC** [comment]
Dup of https://github.com/Ferrite-FEM/Ferrite.jl/issues/278 maybe?

**Comment by termi-official** [comment]
Derp.
