### ISSUE TITLE
Poor performance of converting Gmsh grid to Ferrite grid

### ISSUE THREAD

**Issue by darthvlado** [Ferrite-FEM/Ferrite.jl#770]
Mesh conversion using the **togrid()** function takes several orders of magnitude more time than generating this mesh using Gmsh. I doubt this should be the case. The grid is quite simple - a cube from which a cone is extruded. Below is a minimal working example.

```
using Gmsh
using FerriteGmsh

function setup_grid(hR, Z, r)
    gmsh.initialize()
    gmsh.model.add("mesh")

    gmsh.model.occ.addBox(
        -0.5, -0.5, 0.0-hR,
        1., 1., Z,   
        1)
    gmsh.model.occ.addCone(
        0., 0., 0.0-hR, 
        0.,0.,hR,
        r,0.,
        2)
    gmsh.model.occ.cut([(3,1)], [(3,2)], 3)
   
    gmsh.model.occ.synchronize()

    gmsh.model.addPhysicalGroup(3, [3], -1, "sample")
    gmsh.model.addPhysicalGroup(2, [1], -1, "leftX")
    gmsh.model.addPhysicalGroup(2, [2], -1, "leftY")
    gmsh.model.addPhysicalGroup(2, [3], -1, "topZ")
    gmsh.model.addPhysicalGroup(2, [4], -1, "rightY")
    gmsh.model.addPhysicalGroup(2, [5,7], -1, "bottomZ")
    gmsh.model.addPhysicalGroup(2, [6], -1, "rightX")

    gmsh.model.mesh.setSizeCallback((dim, tag, x, y, z, lc) -> 0.07)
    gmsh.model.mesh.generate(3)
    gmsh.write("mesh.msh")
    gmsh.finalize()

    @time grid = togrid("mesh.msh")
    return grid
end

@time setup_grid(1, 2, 0.4)
```

On my computer the mesh is generated in 0.03 seconds but converted in 23 seconds.

**Comment by termi-official** [comment]
Hi @darthvlado , thanks for reporting this. It is a known problem in FerriteGmsh.jl, likely due to type instabilities during grid conversion, but we cannot find time to fix the issue.

**Comment by termi-official** [comment]
Btw a workaround for now is to generate the Ferrite grid once and store it with [JLD2](https://github.com/JuliaIO/JLD2.jl) or some other format - or just write out the elements and cells.
