### ISSUE TITLE
Implement FaceQuadratureRule for RefPrism and RefPyramid

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#772]
Currently, `FaceQuadratureRule{RefPrism}(2)` yields `ERROR: FaceQuadratureRule for RefPrism not implemented`

**Comment by AbdAlazezAhmed** [comment]
Working on it in the PR
Did some tests and it seems to work, will push it in the next commit of everything works :D

**Comment by KnutAM** [comment]
Nice! Perhaps it could be a separate pr though to simplify the review?

**Comment by AbdAlazezAhmed** [comment]
The thing is that I made `create_face_quad_rule` use
https://github.com/Ferrite-FEM/Ferrite.jl/blob/a2d16d31b7654f4f7cff54214f9e56e8d51e3613/src/Grid/grid.jl#L865-L919
to avoid having multiple functions doing the same thing, so it depends on it. Maybe I can take it too in the PR.

**Comment by KnutAM** [comment]
That is a very nice solution! (Perhaps those functions should be put next to where the reference coordinates are defined though instead of in `grid.jl`?)

If it is too difficult to separate then it is not necessary, especially if #743 is close to being ready but relies on this to be implemented as well. If not close, then re-working the `create_face_quad_rule` function to utilize these functions in a separate pr would make sense to me.

**Comment by AbdAlazezAhmed** [comment]
Almost done, some tests fail for normals and face area for the last two faces. I assume this has to do with me not understanding how `weighted_norma()` works and doing it with intuition <img src="https://static.thenounproject.com/png/105262-200.png" width="30" 
     height="30"> * I mean I get that it's a normal (cross product) weighted by the volume ration (the jacobian) IIUC, but I don't get the issue for some reason, maybe I need to think about it for more time :"D *

```julia
function weighted_normal(J::Tensor{2,3}, ::Type{RefPyramid}, face::Int)
    @inbounds begin
        face == 1 && return J[:,2] × J[:,1]
        face == 2 && return J[:,1] × J[:,3]
        face == 3 && return J[:,3] × J[:,2]
        face == 4 && return J[:,2] × J[:,3]
        face == 5 && return J[:,3] × J[:,1]
    end
    throw(ArgumentError("unknown face number: $face"))
end
```     

The transformation:
```julia
"""
Mapping from 2D face to 3D face of a pyramid.
"""
function transfer_point_face_to_cell(point::Union{Vec{2, Float64}, Vector{Float64}}, cell::Union{AbstractCell{RefPyramid}, Type{RefPyramid}}, face::Int)
    x,y = point
    face == 1 && return Vec( (y+1)/2,   (x+1)/2,    0.0)
    face == 2 && return Vec( y,         0.0,        1-x-y)
    face == 3 && return Vec( 0.0,       1-x-y,      y)
    face == 4 && return Vec( x+y,       y,          1-x-y)
    face == 5 && return Vec( 1-x-y,     1-y,        y)
    error("Face index $face exceeds the number of faces for a cell of type $(typeof(cell))")
end
```
The normals/area tests fail for faces 4 & 5 only.

**Comment by KnutAM** [comment]
Yes, it is not that simple for faces not aligned with the coordinate axis, see 
https://github.com/Ferrite-FEM/Ferrite.jl/blob/d474caf357c696cdb80d7c5e1edcbc7b4c91af6b/src/FEValues/face_integrals.jl#L143-L150

**Comment by AbdAlazezAhmed** [comment]
Thanks!
```julia
function weighted_normal(J::Tensor{2,3}, ::Type{RefPyramid}, face::Int)
    @inbounds begin
        face == 1 && return J[:,2] × J[:,1]
        face == 2 && return J[:,1] × J[:,3]
        face == 3 && return J[:,3] × J[:,2]
        face == 4 && return J[:,2] × (J[:,3]-J[:,1])
        face == 5 && return (J[:,3]-J[:,2]) × (J[:,1]+J[:,2]-J[:,3])
    end
    throw(ArgumentError("unknown face number: $face"))
end
```
worked! I'll do the prism one and if everything works will open a PR.

**Comment by KnutAM** [comment]
Cool! I guess using the same logic as for face == 4, face 5 could be `(J[:,3]-J[:,2]) × J[:,1]`?
Should give the same value, because `(J[:,3]-J[:,2]) × (J[:,2]-J[:,3]) = 0`
