### ISSUE TITLE
Go to definition problems

### ISSUE THREAD

**Issue by andreichalapco** [Ferrite-FEM/Ferrite.jl#773]
I was currently going through the tutorials where we define the reference cube and I noticed that some go to definition functionality is missing:

when doing go to definition (within vs code with Julia language server enabled I can't access the lagrange)

```
ip = Lagrange{dim, RefCube, 2}()
```

This is also the case for quadrature rule

**Comment by fredrikekre** [comment]
Interesting, works for other structs (like `RefCube` in that code snippet). I don't see how this could be a Ferrite problem though, perhaps you can report it to https://github.com/julia-vscode/LanguageServer.jl ?
