### ISSUE TITLE
Solutions of the assembled systems are misaligned/corrupted

### ISSUE THREAD

**Issue by suurj** [Ferrite-FEM/Ferrite.jl#777]
Let us consider the following simple code to solve the steady-state heat equation with a mesh TestMesh.msh imported from Gmsh. The mesh can be found in the attachment below. The boundaries of the mesh have been labeled as right, top, left, and bottom to agree with the meshes generated by the function `generate_grid.` The left and right boundaries are set with Dirichlet boundary conditions, and the top and bottom boundaries are assumed to have Neumann boundary conditions with zero flux.

```
using Ferrite, SparseArrays
using PyPlot
using FerriteGmsh

#grid = generate_grid(Triangle, (10, 10),Vec{2}((-1.0,-1.0)), Vec{2}(( 1.0, 1.0))); # For comparison
grid = togrid("TestMesh.msh")

degree = 1
dim = 2

type = RefTetrahedron
ip = Lagrange{dim, type, degree}()
qr = QuadratureRule{dim, type}(2)
cellvalues = CellScalarValues(qr, ip);

dh = DofHandler(grid)
add!(dh, :u, 1,ip)
close!(dh)

K = create_sparsity_pattern(dh)
ch = ConstraintHandler(dh);

dbc = Dirichlet(:u, getfaceset(grid, "left"), (x, t) -> 0.0)
dbc2 = Dirichlet(:u, getfaceset(grid, "right"), (x, t) -> 1.0)

add!(ch, dbc);
add!(ch, dbc2);
close!(ch)

function assemble_element!(Ke::Matrix, fe::Vector, cellvalues::CellScalarValues)
    n_basefuncs = getnbasefunctions(cellvalues)
    # Reset to 0
    fill!(Ke, 0)
    fill!(fe, 0)
    # Loop over quadrature points
    for q_point in 1:getnquadpoints(cellvalues)
        # Get the quadrature weight
        dΩ = getdetJdV(cellvalues, q_point)
        # Loop over test shape functions
        for i in 1:n_basefuncs
            δu  = shape_value(cellvalues, q_point, i)
            ∇δu = shape_gradient(cellvalues, q_point, i)
            # Add contribution to fe
            fe[i] += δu * dΩ
            # Loop over trial shape functions
            for j in 1:n_basefuncs
                ∇u = shape_gradient(cellvalues, q_point, j)
                # Add contribution to Ke
                Ke[i, j] += (∇δu ⋅ ∇u) * dΩ
            end
        end
    end
    return Ke, fe
end

function assemble_global(cellvalues::CellScalarValues, K::SparseMatrixCSC, dh::DofHandler)
    # Allocate the element stiffness matrix and element force vector
    n_basefuncs = getnbasefunctions(cellvalues)
    Ke = zeros(n_basefuncs, n_basefuncs)
    fe = zeros(n_basefuncs)
    # Allocate global force vector f
    f = zeros(ndofs(dh))
    # Create an assembler
    assembler = start_assemble(K, f)
    # Loop over all cels
    for cell in CellIterator(dh)
        # Reinitialize cellvalues for this cell
        reinit!(cellvalues, cell)
        # Compute element contribution
        assemble_element!(Ke, fe, cellvalues)
        # Assemble Ke and fe into K and f
        assemble!(assembler, celldofs(cell), Ke, fe)
    end
    return K, f
end

K, f = assemble_global(cellvalues, K, dh);
apply!(K, f, ch)
u = K \ f;

N = length(u)
pts = hcat([ grid.nodes[i].x for i in 1:N]...)

tricontourf(pts[1,:],pts[2,:],u,levels=100)
colorbar()
```

If the PDE is solved with the imported mesh, the solution seems not to agree at all with the mesh nodes. The solution (solution_with_the_imported_mesh.png) should be close to one at the right boundary, which is not the case.

Additionally, if the function generate_mesh is used, the solution (solution_with_generate_grid.png) is otherwise good, but there is an unphysical "strip" with values close to 1 near the bottom boundary of the mesh. If the mesh is refined, the height of the strip decreases, so the issue might be related to the nodes next to those located on the bottom boundary. 

Do you have any ideas what might be the reason?
![solution_with_generate_grid](https://github.com/Ferrite-FEM/Ferrite.jl/assets/40865346/533cf7a3-47f3-40e4-a25f-b63dd2618bd7)
![solution_with_the_imported_mesh](https://github.com/Ferrite-FEM/Ferrite.jl/assets/40865346/5ddaa266-5c61-4118-bce5-02e9cb46d74e)
[TestMesh.msh.zip](https://github.com/Ferrite-FEM/Ferrite.jl/files/12207153/TestMesh.msh.zip)

**Comment by fredrikekre** [comment]
> Do you have any ideas what might be the reason?

Degrees of freedom numbering do *not* match the numbering of the nodes. While this would be possible in simple cases it doesn't work in general. This is why the DofHandler must be used when exporting.

I can post a code snippet later which evaluates the function in the grid nodes.

**Comment by koehlerson** [comment]
As Fredrik said, you need the DofHandler. You have two options that just work:

1. FerriteViz where you can have plots with Makie, just add to your script:
```julia
plotter = FerriteViz.MakiePlotter(dh,u)
fig, ax, sp = FerriteViz.solutionplot(dh,u)
```
or whatever plot type you like, e.g. try `surface` instead of `surfaceplot` and you see that the solution is absolutely fine and in line with the one from the `generate_grid` one:
![grafik](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/62bb4843-08e4-45d3-a715-8a70f9eeb86b)

2. VTK export and visualization in ParaView is the more classical way where you can follow the examples from the documentation and attach to your code 

```
vtk_grid("test", dh) do vtk
    vtk_point_data(vtk, dh, u)
end
```

and if you take a look at your Gmsh generated mesh, you will see that the assumption of dof ordering = node ordering breaks already with the second node:

![grafik](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/7c35ff3e-70de-4030-b013-b72c952a65a2)

If you still want to use `PyPlot` for some reason, you can make use of the FerriteViz internals or copy paste the following function: https://github.com/Ferrite-FEM/FerriteViz.jl/blob/master/src/utils.jl#L541-L559

**Comment by suurj** [comment]
Many thanks for the replies, I think I udnerstand the rationale now. I made three functions to evaluate the values in the grid nodes.

```
function pointeval(dh,pointvalues,ph,u)
    n = getnbasefunctions(pointvalues.cv)
    cell_dofs = zeros(Int, n)

    vals = zeros(length(ph.local_coords))
    for (i, point) in enumerate(PointIterator(ph))
        point === nothing && continue 
        reinit!(pointvalues, point)   
        celldofs!(cell_dofs, dh, point.cid)
        ue = u[cell_dofs]
        f = function_value(pointvalues,1,ue)
        vals[i] = f
    end

    return vals
end

```

points = [grid.nodes[i].x for i in 1:length(grid.nodes)]
ph = PointEvalHandler(grid, points);
up1 = Ferrite.get_point_values(ph, dh, u, :u)[:]
up2 = reshape_to_nodes(dh,u,:u)[:]
up3 = pointeval(dh,pointvalues,ph,u)
# All three agree with each other

**Comment by suurj** [comment]
Because the reason for the problem was found, I hence close the issue.
