### ISSUE TITLE
Simplify deduction of eltype in FunctionValues constructor

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#857]
In #764, a potential simplification of the code linked below was [discussed](https://github.com/Ferrite-FEM/Ferrite.jl/pull/764#discussion_r1416922810). Would be good to investigate, but this should also become simpler if https://github.com/Ferrite-FEM/Tensors.jl/pull/188 is finalized. CC @termi-official 

https://github.com/Ferrite-FEM/Ferrite.jl/blob/324bd4a11f24f45f4688ca045b71ce7dde4b6960/src/FEValues/FunctionValues.jl#L8-L30

**Comment by termi-official** [comment]
>  # Why not ::Vec here? 

The only reason here is literally that I did not want to mix Vec and SMatrix , because of missing support for mixed tensors. :)

**Comment by KnutAM** [comment]
I think for now that is ok, but I talked to @fredrikekre that before releasing 1.0 we should probably add a note in the docs since this will be a breaking change for users of embedded elements when the output changes from SArray to Tensor/MixedTensor. 

E.g. in interface elements (#767 ), they currently return SArrays when they would in the future return `Tensor`.

**Comment by KnutAM** [comment]
> There is also the possibility of vdim > 3 which Tensors don't handle(?)

What is the application of this?
If a generalized Tensor for higher dimensions is needed, that would be easy to add support for using the macro in https://github.com/Ferrite-FEM/Tensors.jl/pull/211.

I would find it better to have a flag on FEValues construction, e.g. `returntype=SArray` (default being e.g. `AbstractTensor`) for such special cases to be very explicit. I find that getting `SArray` for some combinations of dimensions and `Tensor` for others is confusing/unexpected.

**Comment by termi-official** [comment]
The change from SArray to MixedTensor should be non-breaking, because tensors are just SArrays with defined size + some ops, right?

**Comment by KnutAM** [comment]
> The change from SArray to MixedTensor should be non-breaking, because tensors are just SArrays with defined size + some ops, right?

Not really...
```julia
julia> at = rand(Tensor{2,3});

julia> as = rand(SMatrix{3,3});

julia> as * as
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 1.70716  1.13599   1.33628
 1.84993  1.49189   1.3397
 1.42037  0.676446  1.24042

julia> at * at
ERROR: use `⋅` (`\cdot`) for single contraction and `⊡` (`\boxdot`) for double contraction instead of `*`
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] *(S1::Tensor{2, 3, Float64, 9}, S2::Tensor{2, 3, Float64, 9})
   @ Tensors C:\Users\meyer\.julia\packages\Tensors\DZnYM\src\tensor_ops_errors.jl:3
 [3] top-level scope
   @ REPL[6]:1
```
