### ISSUE TITLE
Some of links in documentation are dead

### ISSUE THREAD

**Issue by pnavaro** [Ferrite-FEM/Ferrite.jl#908]
Hi

I organised a seminar next week with @KnutAM and I sent the link https://ferrite-fem.github.io/Ferrite.jl/stable/overview/

Unfortunately all links to examples are dead 😬

Pierre

**Comment by KristofferC** [comment]
I thought that should have been fixed https://github.com/Ferrite-FEM/Ferrite.jl/issues/744

You can use https://ferrite-fem.github.io/Ferrite.jl/dev/tutorials/ in the mean time.,

**Comment by koehlerson** [comment]
yeah it's fixed on master but not in the `stable` deploy

**Comment by KnutAM** [comment]
Isn't there a quick way to fix this? 
Can I e.g. tag v0.3.14_docsrev on a branch fixing this (originating from the v0.3.14 tag commit). Would documenter pick this up?

**Comment by fredrikekre** [comment]
Fixed
