### ISSUE TITLE
Release v0.4 or wait to finish 1.0?

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#909]
Just to have the discussion...

There are some bugs that are fixed on master + some issues with docs (e.g. #908).

It seems like there are some more things that would be good to get into 1.0, so it is still a bit away. 

Would an alternative be to release v0.4 now, and then accept that there will be a second round of breaking changes before v1.0 which we could aim to release at/before FerriteCon2024?

**Comment by termi-official** [comment]
xref https://github.com/Ferrite-FEM/Ferrite.jl/pulls?q=is%3Aopen+is%3Apr+milestone%3Av1.0.0

**Comment by koehlerson** [comment]
should be #780 part of 1.0 milestone?

**Comment by fredrikekre** [comment]
I think at this point only breaking things should be holding up 1.0. I believe #780 only adds new features right?

**Comment by koehlerson** [comment]
https://github.com/Ferrite-FEM/Ferrite.jl/pull/780/files#diff-8db5ed06971ce1004169862f3e499f55666dd630868843be8a53d30ea385e505R110-R119

so this would be okay after 1.0 ?

**Comment by KnutAM** [comment]
I'm soon posting an extension of @lijas' #789 which will be pretty breaking. 
So an argument against releasing an intermediate step (if this should be included) is that this would introduce FacetValues replacing FaceValues, but FaceValues currently replaces FaceVectorValues and FaceScalarValues on master, so that gives two breaking changes which would only be one otherwise...

**Comment by KnutAM** [comment]
Looks like we will do a 1.0, so closing this.
