### ISSUE TITLE
Don't promise to not change fields in Grid

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#918]
xref https://github.com/Ferrite-FEM/Ferrite.jl/pull/916#discussion_r1604457342

In https://ferrite-fem.github.io/Ferrite.jl/stable/manual/grid/#AbstractGrid we state "In case that certain structures are preserved from the Ferrite.Grid type, you don't need to dispatch on your own type, but rather rely on the fallback AbstractGrid dispatch."

Before releasing 1.0 we should probably relax this statement such that we can change fields in the Grid without that being considered a breaking change. Opening this issue and tagging it with 1.0 to ensure that we remember before releasing.

**Comment by termi-official** [comment]
If I remember the discussion on this correctly, then this is exactly the guarantee which @fredrikekre wants to enforce. I also think that this is a sensible default. xref https://github.com/Ferrite-FEM/Ferrite.jl/pull/916#discussion_r1604796117

**Comment by KnutAM** [comment]
You are right: We have documented the fields in `Grid` explicitly, so this is public API. 
Changing that is more than changing this statement!
