### ISSUE TITLE
Changelog for face -> facet changes

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#919]
#914 is missing changelog entries for user-facing changes:
 - `getfaceset` -> `getfacetset`, `addfaceset!` -> `addfacetset!`
 - `addboundaryfaceset!` -> `addboundaryfacetset!`
 - `getedgeset`, `addedgeset!`, `addboundaryedgeset`
   No direct replacement, but `Ferrite.create_edgeset` and `Ferrite.create_boundaryedgeset` gives equivalent functionality (for 3d cases) for sets not stored in the grid.
 - `FaceValues` -> `FacetValues`
 - `AbstractFacetValues` -> `AbstractFacetValues` (why is this exported?)
 - `Ferrite.getcurrentface` -> `Ferrite.getcurrentfacet`
 - `FaceQuadratureRule` -> `FacetQuadratureRule`
 - `nfaces` -> `nfacets`
 - `FaceIterator` -> `FacetIterator`
 - `FaceCache` -> `FacetCache`
 - `collect_periodic_faces` -> `collect_periodic_facets`
 - `PeriodicFacePair` -> `PeriodicFacetPair` (why is this exported?)

Anything else?

**Comment by termi-official** [comment]
Yea, I would also vote for removing such "global" queries on the grid, since they cause more harm than good. Or we rename then to "max_faces_per_cell" or smth, which could be used to create buffers which are "large enough".

**Comment by KnutAM** [comment]
Removed in #921

**Comment by KnutAM** [comment]
Closed in #940
