### ISSUE TITLE
getdim consistency

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#936]
Currently we have 
```julia
[1] getdim(g::Ferrite.AbstractGrid)
[2] getdim(::Union{Ferrite.AbstractCell{refshape}, Type{<:Ferrite.AbstractCell{refshape}}}) where {refdim, refshape<:Ferrite.AbstractRefShape{refdim}}
[3] getdim(::Interpolation{shape}) where {dim, shape<:Ferrite.AbstractRefShape{dim}}
```
from `methods(Ferrite.getdim)`, but only [3] is documented. [2,3] returns the reference dim and [1] returns `g's` spatial dimension. 

I would suggest replacing [1] by `getsdim(::AbstractGrid)` (public, not exported)

For consistency, `getrdim` would make sense for [2,3], but probably an uncessary breaking change and ok if we don't mix definitions. 

(After #914, we have the internal `Ferrite.get_reference_dimension(::AbstractGrid)`, but this may also return `:mixed` if there are cells with different rdims in the grid, so probably not good as public api, and can in any case be needed later). 

Thoughts?

**Comment by termi-official** [comment]
Since we have split the interface before and have the inconsistency now I think it is justifiable to break in favor of a clearer interface. Note that for [3] users might confuse `getdim` with the vector dimension. I am not sure about getrdim for the grid tho, it seems to be error prone. We should highlight the design in the docs anyway.

**Comment by fredrikekre** [comment]
Why not ` getrdim` and `getsdim`? Or `get_reference_dimension` and `get_spatial_dimension`?

**Comment by lijas** [comment]
Isn't the return value from`getdim` always clear from the input arguments? In the code I usually do:
```
sdim = getdim(grid)
rdim = getdim(cell)
```

**Comment by KnutAM** [comment]
> I am not sure about getrdim for the grid tho, it seems to be error prone

If included, I would suggest to have this method error when the grid doesn't have a single reference dim, e.g. 
```julia
function getdim(g::AbstractGrid)
    # Originally, I called the following function `get_reference_dimensionality` to distinguish 
    # from getrdim, could also be `get_reference_diminfo` of something like that...
    rdim = get_reference_dimension(g)
    if rdim isa Int
        return rdim
    else
        throw(ArgumentError("getrdim is only defined for grids with a single reference dimension"))
    end
end
```

**Comment by fredrikekre** [comment]
Even if you probably can have the same function name it is clearer to have separate names IMO.

> getfielddim

This returns 1 for 0-dimensional (scalar) fields so this is more "number of components" (we have `n_components` for the interpolations I think?)

**Comment by KnutAM** [comment]
> This returns 1 for 0-dimensional (scalar) fields so this is more "number of components" (we have n_components for the interpolations I think?)

True! 
I would say that scalar fields are 0th order though, and not 0-dimensional (following Tensors.jl). From that perspective it shouldn't even be defined? 

So for consistency, we should actually rename `getfielddim(::AbstractDofHandler, field_idx)` to `n_components` as this is what it is returning? This will be an even more important distinction when introducing 2nd order tensor interpolations in the future!

**Comment by termi-official** [comment]
> > This returns 1 for 0-dimensional (scalar) fields so this is more "number of components" (we have n_components for the interpolations I think?)
> 
> True! I would say that scalar fields are 0th order though, and not 0-dimensional (following Tensors.jl). From that perspective it shouldn't even be defined?
> 
> So for consistency, we should actually rename `getfielddim(::AbstractDofHandler, field_idx)` to `n_components` as this is what it is returning? This will be an even more important distinction when introducing 2nd order tensor interpolations in the future!

Let us quickly think this through with https://github.com/Ferrite-FEM/Ferrite.jl/issues/398 in mind. For a 2D symmetric stress problem formulation you will end up with 3 unknown components. From your expectation, is 3 also the field dimension? Or is it (2,2)? And do you have an example use case where you need this function?

**Comment by KnutAM** [comment]
`n_components` should return the number of scalar values to represent, similar to `Tensors.n_components` IMO, so for symmetric stress problems in non-embedded 2d: 3. 
For this case, I expect the dimension to be 2 mirroring the dimension in Tensors. 

Currently, we don't really have a function for this then, but since the output of `Ferrite.n_components(ip)` is the same as `Ferrite.getfielddim(dh, field_name)`, I think it would make sense to redefine `Ferrite.getfielddim(dh, field_name)` to `Ferrite.n_components(dh, field_name)`, since it doesn't really give the dimension as @fredrikekre points out). 

At the moment, I don't think we need to introduce `getfielddim` then (which is also nice to not directly change the meaning, but can be done once matrix-valued / higher order tensor interpolations are introduced (if needed at that time).
