### ISSUE TITLE
fix topology getneighborhood call in 2D

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/Ferrite.jl#941]
The renaming of the entities leads to a wrong code branch for `getneighborhood(top,grid,facetidx)` if the grid is in 2D. This is due to the fact that the `facetidx` is converted to an `edgeidx` and then an edge neighborhood reconstruction is built which was only designed for the three dimensional case.

https://github.com/Ferrite-FEM/Ferrite.jl/blob/68e1ab15bea4618f76b9ed1d850e2ce33375e266/src/Grid/topology.jl#L282-L292

What should be done is this:

https://github.com/Ferrite-FEM/Ferrite.jl/blob/68e1ab15bea4618f76b9ed1d850e2ce33375e266/src/Grid/topology.jl#L259-L263

but with the `edge_edge` table in 2D. Some dispatch distinction for 2D and 3D for an `EdgeIndex` should be enough. Some regression testing should be included. It could be that the first, wrong code branch returns the same as the intended one, problem for me is that there are assumptions about the grid type that I don't fulfill in the p4est branch, and that's why I noticed this. It should be changed anyway for performance reasons.

**Comment by koehlerson** [comment]
Context for the first code branch is that some edge neighborhood is reconstructed, since the table only stores the exclusively connected element via the edge. However, there are more elements connected by this edge (but also by a face)

**Comment by KnutAM** [comment]
I'm not sure if I understand when this will fail. Which assumptions are you talking about? 
Do you have a specific case showing the that we could test for? 

Regarding the performance, that is clear
```julia
grid = generate_grid(Quadrilateral, (2,2));
top = ExclusiveTopology(grid);
```
Latest release (btiming: `55.127 ns (2 allocations: 128 bytes)`)
```julia
julia> getneighborhood(top, grid, FaceIndex(1, 2), true)
2-element Vector{FaceIndex}:
 FaceIndex((2, 4))
 FaceIndex((1, 2))
```
Master (btiming: `363.636 ns (19 allocations: 1.50 KiB)`)
```julia
julia> getneighborhood(top, grid, FacetIndex(1, 2), true)
2-element Vector{EdgeIndex}:
 EdgeIndex((2, 4))
 EdgeIndex((1, 2))
```

**Comment by koehlerson** [comment]
> I'm not sure if I understand when this will fail. Which assumptions are you talking about? Do you have a specific case showing the that we could test for?

It fails if you cannot fulfill what is expected of a `cell`, because `edges` is called on a cell. The adaptive cells don't know what their global edge ids are. This doesn't matter too much, since the computations done in the code branch don't make sense anyway. The problem is how to test it

**Comment by bplcn** [comment]
Hi! Recently I have tryed the adaptive mesh. However I find that there is something wrong with the hanging nodes. The balance tree failures at some edges. Is it something to do with the getneighborhood function?

<img width="298" alt="屏幕截图 2024-06-12 143119" src="https://github.com/Ferrite-FEM/Ferrite.jl/assets/47040923/16bcd2e8-40a5-485c-a99e-de35509360e8">

**Comment by koehlerson** [comment]
Have you tried on the latest `mk/p4est` commit ?

**Comment by koehlerson** [comment]
> Hi! Recently I have tryed the adaptive mesh. However I find that there is something wrong with the hanging nodes. The balance tree failures at some edges. Is it something to do with the getneighborhood function?
> <img alt="屏幕截图 2024-06-12 143119" width="298" src="https://private-user-images.githubusercontent.com/47040923/338856448-16bcd2e8-40a5-485c-a99e-de35509360e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzc4NjAsIm5iZiI6MTcxODE3NzU2MCwicGF0aCI6Ii80NzA0MDkyMy8zMzg4NTY0NDgtMTZiY2QyZTgtNDBhNS00ODVjLWE5OWUtZGUzNTUwOTM2MGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZjhhNTQzZmM3ODEzMDFmMDk5NzJmNzZlYjVlYjFiZjE5NDBkNzg0MzVhMDI3ZWM4NWRmYTNiZWI0ODE4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dK6I9ht1hotKgacS4OSgQPxtNi8D-knZJiOqPof7Gs">

To answer the question: I don't think it is related to the function, since I explicitly call the neighborhood tables now. It's more likely that this is a bug from an old commit, that is hopefully fixed on a more recent commit. There were some leftover cases in the balancing code which didn't take care of some hanging nodes. Maybe it's a bug that hasn't been fixed. Is that the adaptivity example from the docs?

**Comment by bplcn** [comment]
> > Hi! Recently I have tryed the adaptive mesh. However I find that there is something wrong with the hanging nodes. The balance tree failures at some edges. Is it something to do with the getneighborhood function?
> > <img alt="屏幕截图 2024-06-12 143119" width="298" src="https://private-user-images.githubusercontent.com/47040923/338856448-16bcd2e8-40a5-485c-a99e-de35509360e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzc4NjAsIm5iZiI6MTcxODE3NzU2MCwicGF0aCI6Ii80NzA0MDkyMy8zMzg4NTY0NDgtMTZiY2QyZTgtNDBhNS00ODVjLWE5OWUtZGUzNTUwOTM2MGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZjhhNTQzZmM3ODEzMDFmMDk5NzJmNzZlYjVlYjFiZjE5NDBkNzg0MzVhMDI3ZWM4NWRmYTNiZWI0ODE4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dK6I9ht1hotKgacS4OSgQPxtNi8D-knZJiOqPof7Gs">
> 
> To answer the question: I don't think it is related to the function, since I explicitly call the neighborhood tables now. It's more likely that this is a bug from an old commit, that is hopefully fixed on a more recent commit. There were some leftover cases in the balancing code which didn't take care of some hanging nodes. Maybe it's a bug that hasn't been fixed. Is that the adaptivity example from the docs?

No, it not from the doc examples. The examples works all right.

**Comment by koehlerson** [comment]
Interesting, do you have a MWE?

**Comment by bplcn** [comment]
> Interesting, do you have a MWE?

No. What is the MWE ?  :)

**Comment by koehlerson** [comment]
ah sorry! minimum working example such that I can try to reproduce the non-balanced case :)

**Comment by bplcn** [comment]
> ah sorry! minimum working example such that I can try to reproduce the non-balanced case :)

OK, I will prepare for it as quick as possible.

**Comment by bplcn** [comment]
Following is the script for the AMR process
```julia

using Ferrite, FerriteMeshParser
using DelimitedFiles

function iniatial_refine!(adaptive_grid, region_func; lmin=0.01)

    ip = Lagrange{RefQuadrilateral, 1}()
    qr = QuadratureRule{RefQuadrilateral}(2)
    cv = CellValues(qr, ip)

    ifVec = [false,false,false,false]

    for k = 1:100

        @info k

        marked_cells = Vector{Int64}()

        grid = Ferrite.creategrid(adaptive_grid) 

        dh = DofHandler(grid)
            add!(dh, :p, ip)
        close!(dh)

        cc = CellCache(dh)

        for cellid in 1:getncells(grid)
            reinit!(cc, cellid)
            reinit!(cv, cc)

            coords = getcoordinates(cc)

            for (i, x) in enumerate(coords)
                ifVec[i] = region_func(x)
            end

            if_close = true in ifVec

            for q_point in 1:getnquadpoints(cv)
                dΩ = getdetJdV(cv, q_point) #wᵢ * Jξ
                le = sqrt(dΩ)*2 
                ifVec[q_point] = le > lmin
            end

            if (true in ifVec) && if_close
                push!(marked_cells, cellid)
            end
        end

        if_refine = ~isempty(marked_cells)

        if ~if_refine
            break
        end

        # update the grid and buffer infomation
        Ferrite.refine!(adaptive_grid, marked_cells)
        Ferrite.balanceforest!(adaptive_grid)

    end

end

# Read the mesh file
grid_ini = get_ferrite_grid("snep.inp");
adaptive_grid = ForestBWG(grid_ini,#=maxlevel=#15);

if_in_reg_fun(x) =  abs(x[2]) < 0.01 && abs(x[1]) < 0.01

iniatial_refine!(adaptive_grid, if_in_reg_fun; lmin=0.0025)

grid_ini_fine = Ferrite.creategrid(adaptive_grid) 
ip = Lagrange{RefQuadrilateral, 1}()
dh = DofHandler(grid_ini_fine)
    add!(dh, :p, ip)
close!(dh)

VTKFile("ini_mesh", dh) do vtk
end

data = readdlm("marked_cell.txt",',')
n_refine = size(data, 1)
n_max_elem = size(data, 2)
marked_cell_Vec = Vector{Vector{Int64}}()
for k_refine in 1:n_refine
    mark_cells_now = Vector{Int64}()
    for kelem in 1:n_max_elem
        if ~isempty(data[k_refine, kelem])
            push!(mark_cells_now, data[k_refine, kelem])
        end
    end
    push!(marked_cell_Vec, mark_cells_now)
end

pvd = VTKFileCollection("ada.pvd", grid_ini_fine);
for k_refine in 1:n_refine
    @info k_refine
    Ferrite.refine!(adaptive_grid, marked_cell_Vec[k_refine])
    Ferrite.balanceforest!(adaptive_grid)
    grid = Ferrite.creategrid(adaptive_grid) 
    dh = DofHandler(grid)
    add!(dh, :p, ip)
    close!(dh)
    
    vtk = VTKFile("test/ada-$(k_refine)", grid) 
    addstep!(pvd,vtk,k_refine)
end
close(pvd)

```
[awe.zip](https://github.com/user-attachments/files/15803512/awe.zip)

The whole package is attached, which includes the mesh for each iteration. The edge belongs to cell 207(+1).   I think that there may be some problem with the balance_tree! function.

**Comment by koehlerson** [comment]
@termi-official and me found the problem (at least we think so). The last picture of my latest post is your initial grid, is that correct? If so, then you already start from a non-conforming grid, i.e. included hanging nodes. You need to start from a grid without hanging nodes. The topology can only handle conforming meshes and the adaptive approach relies quite heavily on the topology object

**Comment by koehlerson** [comment]
@KnutAM maybe worth to include in https://github.com/Ferrite-FEM/Ferrite.jl/pull/974 when working on the `ExclusiveTopology` docs a note or warning that the stuff only works for conforming grids

**Comment by bplcn** [comment]
> @termi-official and me found the problem (at least we think so). The last picture of my latest post is your initial grid, is that correct? If so, then you already start from a non-conforming grid, i.e. included hanging nodes. You need to start from a grid without hanging nodes. The topology can only handle conforming meshes and the adaptive approach relies quite heavily on the topology object

![image](https://github.com/Ferrite-FEM/Ferrite.jl/assets/47040923/ed9c47d8-8c40-4bbf-964c-9cc059283f2e)


The initial grid here is the .inp file `snep.inp`, which is a conforming one. Then the mesh is read and the mesh of center region (|x| < 0.01 and |y| <0.01 ) is refiened at first. After that the refined area will expand. So I think the initial mesh may not lead to the unbalance. The unbalanced mesh only appears at the last frame.  I noticed the problem because it will lead to the error of nested affine constrain.

**Comment by koehlerson** [comment]
sorry for the confusion @bplcn ! I took a closer look and I think I resolved the issue on the latest commit of `mk/p4est`. It was some remainding logical error when the balancing happens. Specifically, the problem was that in case of refinement due to balancing another non-conformity is introduced, the check was wrong that something is "still happening" in the balancing. Could you please try the latest commit again with your code? The example works now for me:

pre balance 
![image](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/993a3d92-7292-4beb-a74b-6779994707c8)

Now a vertex balance is triggered where the arrow tip points to, which leads on the previous version to 
![image](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/97c63ec2-dc7e-4c86-a58e-31051f8d240b)

and now on the latest version you should get
![image](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/d6fc1eea-a75b-458e-905b-7a85d7bc81be)

**Comment by bplcn** [comment]
> sorry for the confusion @bplcn ! I took a closer look and I think I resolved the issue on the latest commit of `mk/p4est`. It was some remaining logical error when the balancing happens. Specifically, the problem was that in case of refinement due to balancing another non-conformity is introduced, the check was wrong that something is "still happening" in the balancing. Could you please try the latest commit again with your code? The example works now for me:
> 
> pre balance ![image](https://private-user-images.githubusercontent.com/27497290/339327941-993a3d92-7292-4beb-a74b-6779994707c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTIxOTUsIm5iZiI6MTcxODI5MTg5NSwicGF0aCI6Ii8yNzQ5NzI5MC8zMzkzMjc5NDEtOTkzYTNkOTItNzI5Mi00YmViLWE3NGItNjc3OTk5NDcwN2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MTE2ZTJmMzYyZDdlMTNkOGRiNTYwNmMxMjBjOGNmOWYxMDUxNzg5NDdlNTZlZDFjYTA5ODQ2N2I2ZjM5YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-m0DRBrm6Zfta8vVFqxXQjI0R8szQdh_6TLtyZjOV7g)
> 
> Now a vertex balance is triggered where the arrow tip points to, which leads on the previous version to ![image](https://private-user-images.githubusercontent.com/27497290/339328175-97c63ec2-dc7e-4c86-a58e-31051f8d240b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTIxOTUsIm5iZiI6MTcxODI5MTg5NSwicGF0aCI6Ii8yNzQ5NzI5MC8zMzkzMjgxNzUtOTdjNjNlYzItZGM3ZS00Yzg2LWE1OGUtMzEwNTFmOGQyNDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NmQ4OWI0YjhlYjM1NDkwMzg2YjdiZjljYjVhOGFkMGRlNDY1MjIzMTZmZTNhN2E1NGFkOGQ1NGQzYWE1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rI2lyIccI3NXo9szvXc04b4k8mkDYhO3a84HsFdeIy0)
> 
> and now on the latest version you should get ![image](https://private-user-images.githubusercontent.com/27497290/339328257-d6fc1eea-a75b-458e-905b-7a85d7bc81be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTIxOTUsIm5iZiI6MTcxODI5MTg5NSwicGF0aCI6Ii8yNzQ5NzI5MC8zMzkzMjgyNTctZDZmYzFlZWEtYTc1Yi00NThlLTkwNWItN2E4NWQ3YmM4MWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NDQyMzFmNDAxZTdiMTFkZjAzNGEyYmRkZjNmMzNiZWQ5MmYxOTRjMjJlZTQ5MTY5ZDk0NmFlNGU0NzZjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvfAPMXAfXnl08L7hAhBFq6nnpcllLujGRhFOIe7MaE)

I have tried the last commit. It works all right now and no more errors now. Many thanks!
