### ISSUE TITLE
Error after importing vtu file to paraview

### ISSUE THREAD

**Issue by mithgil** [Ferrite-FEM/Ferrite.jl#986]
After importing to `paraview`, I got error messages:

````
ERROR: In ./VTK/IO/XMLParser/vtkXMLParser.cxx, line 375
vtkXMLDataParser (0x596390b8c540): Error parsing XML in stream at line 20, column 0, byte index 936: not well-formed (invalid token)

ERROR: In ./VTK/IO/XML/vtkXMLReader.cxx, line 521
vtkXMLUnstructuredGridReader (0x5963923bb240): Error parsing input file.  ReadXMLInformation aborting.
````

Could anyone tell me how to fix this issue?

**Comment by koehlerson** [comment]
Which OS do you use? If you are on Arch it could maybe be this: https://gitlab.archlinux.org/archlinux/packaging/packages/vtk/-/issues/4

**Comment by mithgil** [comment]
I am using Ubuntu 22.04.4 LTS now with a x86 CPU.

**Comment by koehlerson** [comment]
Did you download the binaries or installed paraview with the package manager?

**Comment by fredrikekre** [comment]
Looks a lot like https://github.com/JuliaVTK/WriteVTK.jl/issues/136

**Comment by koehlerson** [comment]
I think there is a compat mess up in the latest Paraview release. For me the problem was solved by using the binaries (same for this ubuntu user here: https://stackoverflow.com/questions/78205813/paraview-no-longer-opens-pvtu-files-linux)

**Comment by mithgil** [comment]
Yes, you're right. When I turn to the binary version, everything is good. Thanks.
