### ISSUE TITLE
ExclusiveTopology skeletons

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#988]
While working with ExclusiveTopology in #974, I get the impression that we would only require a single `facet_skeleton::Vector{FacetIndex}`, instead of having separate `vertex_skeleton`, `edge_skeleton`, and `face_skeleton` fields saved. I don't want to do those changes there since unrelated, but unless there is anything I'm missing, I think simplifying that in a later PR would be good...

**Comment by termi-official** [comment]
This boils down to: Is there a cheap algorithm to deduplicate the edges and vertices, given the grid and facet skeleton. Can you sketch the algorithm which you have in mind to achieve this?

**Comment by KnutAM** [comment]
Currently, we only support ExclusiveTopology for grids where all cells have the same reference dimension, and then there is no need to de-duplicate as facet corresponds to vertex, edge, or face - same for all cells.

If we have a grid with cells of different reference dimension, what is actually the definition of any skeleton? 
E.g. if we have 
```julia
(7) --- (8) --- (9)
 |       |       |
 |  4    5    6  7
 |       |       |
(4) --- (5) --- (6)
 |       |       |
 |  1    2    3  |
 |       |       |
(1) --- (2) --- (3)
```
* Is edge (6,9) part of the edge skeleton? (shared between cell 6 and 7)
* Which vertices are part of the vertex skeleton? (All but 1, 3, 7 are shared with at least one other cell)
* For interfaces, the edge (5-8) is part of 3 cells, how should this be handled (currently the code assumes only a single neighbor)

So to me it sounds like the skeleton functionality is tricky for mixed reference dimensions and only makes sense for facets between cells of the same reference dimension. Therefore, we would then rather error for mixed refdim grids on creating the skeleton, even after supporting topology for mixed refdims. 

If the need to combine these two features would come in the future, I guess there will be solutions, which just requires more information from the user side. E.g. the user could pass a cellset or similar to the topology constructor.

**Comment by lijas** [comment]
In adaptivity with hexahedrons, don't you need to find hanging nodes on faces and edges, so only keeping track of facets would not be enough?

**Comment by termi-official** [comment]
> Currently, we only support ExclusiveTopology for grids where all cells have the same reference dimension, and then there is no need to de-duplicate as facet corresponds to vertex, edge, or face - same for all cells.
> 

Taking your example grid above, if I iterate over the edge skeleton, how do I know that I have visited an edge already only with the information with in EdgeIndex?

> If we have a grid with cells of different reference dimension, what is actually the definition of any skeleton? 

A set of unique entities. E.g. for the face skeleton a set with all unique faces.

> In adaptivity with hexahedrons, don't you need to find hanging nodes on faces and edges, so only keeping track of facets would not be enough?

The algorithms for adaptivity indeed need extra information, which is stored in the corresponding data structures. See e.g. https://github.com/Ferrite-FEM/Ferrite.jl/blob/b913af46b2f9257c2ba2ba5f18f1392a288ab8ab/src/Adaptivity/BWG.jl#L795-L919

**Comment by termi-official** [comment]
> Actually, it seems like `vertexskeleton` really doesn't work as intended.
> 
> ```julia
> grid = generate_grid(Quadrilateral, (2,1));
> Ferrite.vertexskeleton(ExclusiveTopology(grid), grid) # Gives 8-element Vector{VertexIndex}:
> ```
> 
> whereas there are only 6 unique vertices in this grid. This should be fixed!
> 

Where does this function even come from? I can only remember providing the face skeleton for DG.

> > A set of unique entities. E.g. for the face skeleton a set with all unique faces.
> 
> Ah, should have known, I got confused since entities without neighbors are skipped by the `InterfaceIterator`. I guess the problem is rather there then, and I simply assumed that this was the only use for the skeleton.
> 

I do not understand the problem here. Can you elaborate?

> Sidetrack, but is it only me who finds skeleton confusing? (It makes sense for facets, but for vertices these are not connected and its sounds strange.) Are `unique_faces`, `unique_edges`, and `unique_vertices` perhaps better?

Skeleton is the name used in literature, so we sticked to it while implementing it.

**Comment by KnutAM** [comment]
> Where does this function even come from? I can only remember providing the face skeleton for DG.

This was included in the massive `face -> facet` pr, because when DG was implemented, facets were called faces, and yes, then it was probably only implemented for faces (now facets). 
This is part of the background as to why I was asking if only providing it for facets would suffice, since that seemed to be the original intention...

> Skeleton is the name used in literature, so we sticked to it while implementing it.
Makes sense!

> I do not understand the problem here. Can you elaborate?
The InterfaceIterator only supports the case of single refdim, hence to me it made sense that the skeleton should also only support single refdim (and then facetskeleton should be enough). But since that errors for mixed refdim, I guess this is ok for now.

**Comment by termi-official** [comment]
> > Where does this function even come from? I can only remember providing the face skeleton for DG.
> 
> This was included in the massive `face -> facet` pr, because when DG was implemented, facets were called faces, and yes, then it was probably only implemented for faces (now facets). This is part of the background as to why I was asking if only providing it for facets would suffice, since that seemed to be the original intention...
> 

Ah, I see. Yes, for now we mostly use the facet skeleton for operations on the trace space (e.g. interface integrals in DG). I know also use-cases where the edge skeleton or the vertex skeleton is needed, but these are really niche (e.g. interaction with generalized finite difference stencils or anisotropic preconditioning) so I think it is okay to just remove the edge and vertex skeleton for now.

> > I do not understand the problem here. Can you elaborate?
> 
> The InterfaceIterator only supports the case of single refdim, hence to me it made sense that the skeleton should also only support single refdim (and then facetskeleton should be enough). But since that errors for mixed refdim, I guess this is ok for now.

Got it, thanks.
