### ISSUE TITLE
Quadrature rule storage type parameter

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/Ferrite.jl#989]
For GPU support of quadrature rules we can simply include the storage type as a type parameter. Since this is technically breaking I propose to include this pre 1.0 if we agree on this.

**Comment by fredrikekre** [comment]
To avoid having a separate type to adapt to? The same could be done for FEValues I think, but perhaps there it is actually useful to have a specific GPU type for dispatch(?).

**Comment by termi-official** [comment]
First this and also to have one data type for the dispatches in Ferrite (as alternative to a supertype, which I think is not necessary here).

Note that we already done this with FEValues, see https://github.com/Ferrite-FEM/Ferrite.jl/blob/54ed4d9d0533fc72572f227bc42e9d5f184ade9f/src/FEValues/FunctionValues.jl#L46-L63 and https://github.com/Ferrite-FEM/Ferrite.jl/blob/54ed4d9d0533fc72572f227bc42e9d5f184ade9f/src/FEValues/CellValues.jl#L44

**Comment by fredrikekre** [comment]
> Note that we already done this with FEValues, see 

Ah, forgot about that.
